### ISSUE TITLE
Mention the use of braces in Conditionals

### ISSUE THREAD

**Issue by creepyLANguy** [reinder42/SwiftCheatsheet#9]
Would be beneficial to state that conditionals can be made more readable by adding braces around each expression, instead of simply saying that they can become confusing if we have multiple expressions (this is currently the case)

**Comment by reinder42** [comment]
Do you mean curly brackets `{ }` or parentheses `( )`? You can use parentheses to change the order of precedence/operations. How would either of them improve readability? Would love to see an example :-)

**Comment by creepyLANguy** [comment]
I mean parenthesis `( )` .

In the current doc :

> Conditionals can be challenging to comprehend. Like this:
> 
>     if c < a && b + c == a
>     {
>         print("Will this ever happen?")
>     }
> 

Parenthesis can make things more readable, especially for those coming familiar with languages that allow the evaluation of operations such as **&&** and **||**, or for those that are simply unsure about the order of operations: 

```
if (c < a) && (b + c == a)
{
    print("Will this ever happen?")
}
```

It's not a hugely important addition, but may be useful to remind people that they can still structure their code in a sensible manner when using Swift.

**Comment by reinder42** [comment]
Thanks for your message! I'm going to add a section about the order of precedence. I'm not a proponent of using parens to make an expression clearer, because you can use those same parens to change the order of operations.

Consider this:

```
2 + 5 * 6 // 32 because 5*6, plus 2
(2 + 5) * 6 // 42 because 2+5=7, times 6
2 + (5 * 6) // nothing changes
```

In the last expression, the parens don't change anything. But, since we want to teach people that parens can change the order of expression – which is it? Clarifying the expression, or changing its order? I think it would confuse people, and teach them a bad technique.

In case of `&&`, `||` and `!` (logical expressions) – those are evaluated after arithmetic and comparison expressions (`+`, `>`, etc.)  That way the individual expressions are evaluated before the whole.

BUT... ;-) I think it's good to point this out in the cheatsheet! I'll add a section on order of precedence, and give some examples of using parentheses.

Thanks!

—Reinder

**Comment by creepyLANguy** [comment]
Makes sense ^^, 
Kudos for being so thorough while maintaing this project.
